--- # FULL INCLUDE TASK EXAMPLE

- hosts: apache
  user: root
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verfiy the telnet package is installed
      raw: yum list installed | grep telnet > /home/test/pkg.log
