--- #My first YAML playbook for ansible
- hosts: apache
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    - playbook_version: 0.1
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: Which pkg do you want to install
  tasks:
    - name: install apache webserver
      action: yum name=httpd state=installed
      notify: restart httpd
    - name:
      action: yum name={{pkg_name}} state=removed
  handlers: 
      - name: restart httpd
        action: service name=httpd state=enable
      - name: restart httpd
        action: service name=httpd state=restarted

        
   
  
   
  
