--- #Until

- hosts: appserver
  sudo: no
  connection: ssh
  user: test
  gather_facts: no
  tasks:
    - name: Installing apache webserver
      yum: pkg=httpd state=latest
    - name: verifiy the status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active(running)") != -1
      retries: 5
      delay: 5
    - debug: var=result

